# Generated by Django 3.0.6 on 2020-05-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwitterUser',
        ),
    ]
