# Generated by Django 3.0.6 on 2020-05-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitterAPI', '0002_delete_twitteruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('search_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
