# Generated by Django 3.0.6 on 2020-05-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterAPI', '0003_twitteruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwitterUser',
        ),
    ]
